In [1]:
import numpy as np

In [2]:
a = np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
b = np.arange(10)
b.resize(5,2)
b
# reshape 在改变形状时，不会影响原数组，相当于对原数组做了一份拷贝。而 resize 则是对原数组执行操作。

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [3]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
np.random.rand(2, 5)

array([[0.88850344, 0.90361314, 0.60851746, 0.09134055, 0.33701656],
       [0.62883912, 0.98764075, 0.24030559, 0.85062874, 0.12010899]])

In [9]:
np.random.randn(9)

array([-0.27448968, -1.35092407, -0.24972964,  0.20406558,  0.33503224,
       -0.55012006, -0.12950658,  0.21930005,  0.66078881])

In [13]:
np.random.randint(2, 5, 5)

array([3, 3, 2, 3, 4])